version: '3.9'

services:
  # api-service:
  #   build:
  #     context: ./services/api
  #     dockerfile: Dockerfile
  #   container_name: api-service
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
  #     - minio
  #     - rabbitmq
  #   networks:
  #     - network

  # diseases-analyzers-service:
  #   build:
  #     context: ./services/diseases-analyzers
  #     dockerfile: Dockerfile
  #   container_name: diseases-analyzer-1-service
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  #     - minio
  #     - rabbitmq
  #   networks:
  #     - network

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=med-app
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=med-app
    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U med-app']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1m

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001' # port for monitoring (web interface)
    networks:
      - network
    environment:
      MINIO_ROOT_USER: access-key
      MINIO_ROOT_PASSWORD: secret-key
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672' # port for monitoring (web interface)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  rabbitmq_data:
